#!/bin/sh

ab="hello"
echo $ab
echo "the program $0 is now running"
echo "the second parameter was $2"
echo "the first parameter was $1"
echo "the parameter list was $*"
echo "the user's home directory is $HOME"

echo "Please enter a new greeting"
read ab

echo $ab
echo "the script is now complete"
exit 0
