.TH MYAPP 1
.SH NAME
Myapp \- A simple demonstration application that does very little.
.SH SYNOPSIS
.B myapp
[\-option ...]
.SH DESCRIPTION
.PP
\fImyapp\fP is a complete application that does nothing useful.
.PP
It was written for demonstration purposes.
.SH OPTIONS
.PP
It doesn't have any, but let's pretend, to make this template complete:
.TP
.BI \-option
If there was an option, it would not be -option.
.SH RESOURCES
.PP
myapp uses almost no resources.
.SH DIAGNOSTICS
The program shouldn't output anything, so if you find it doing so there's probably something wrong. The return value is zero.
.SH SEE ALSO
The only other program we know with this little functionality is the ubiquitous hello world application.
.SH COPYRIGHT
myapp is Copyright (c) 2020 God Publishing, Inc.
.SH BUGS
There probably are some, but we don't know what they are yet.
.SH AUTHORS
God
